# Generated by Django 2.1.3 on 2018-12-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('priority', models.IntegerField()),
            ],
            options={
                'db_table': 'CarouselMap',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hot', models.IntegerField()),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Depot',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('order', models.IntegerField(choices=[(0, '无权限'), (1, '普通员工：查看权限，上架下架'), (2, '仓库管理员：增删改')], default=0)),
                ('posit', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('store_num', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('purchase_date', models.DateTimeField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Depot')),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('introduction', models.CharField(max_length=200, null=True)),
                ('on_date', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('hot', models.IntegerField(default=0)),
                ('off', models.IntegerField(default=0)),
                ('off_cost', models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Category')),
                ('pdepot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Item')),
            ],
            options={
                'db_table': 'Present',
            },
        ),
        migrations.AddField(
            model_name='depot',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Employee'),
        ),
        migrations.AddField(
            model_name='carouselmap',
            name='present',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Present'),
        ),
    ]
