# Generated by Django 2.1.3 on 2018-11-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Depot',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=200)),
                ('emppassword', models.CharField(max_length=200)),
                ('emporder', models.IntegerField(choices=[(0, '无权限'), (1, '普通员工：查看权限，上架下架'), (2, '仓库管理员：增删改')], default=0)),
                ('empposit', models.CharField(max_length=200)),
                ('empphone', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('on_date', models.DateTimeField()),
                ('store_num', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('hot', models.IntegerField(default=0)),
                ('off', models.IntegerField(default=0)),
                ('off_cost', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('pdepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Depot')),
            ],
            options={
                'db_table': 'Present',
            },
        ),
        migrations.AddField(
            model_name='depot',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Employee'),
        ),
    ]
