# Generated by Django 2.1.3 on 2018-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='introduction',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
