# Generated by Django 2.1.3 on 2018-12-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hot',
            field=models.IntegerField(null=True),
        ),
    ]
