# Generated by Django 2.1.3 on 2018-11-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20181119_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('on_date', models.DateTimeField()),
                ('store_num', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('hot', models.IntegerField(default=0)),
                ('off', models.IntegerField(default=0)),
                ('off_cost', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='emploee',
            name='emporder',
            field=models.IntegerField(choices=[(0, '无权限'), (1, '普通员工：查看权限，上架下架'), (2, '仓库管理员：增删改')], default=0),
        ),
    ]
