# Generated by Django 2.1.3 on 2018-11-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_depot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emploee',
            new_name='Employee',
        ),
    ]
